server:
  applicationConnectors:
    - type: http
      port: 8280
  adminConnectors:
    - type: http
      port: 8281

hazelcastSessionConfig:
  # Default is HazelcastSessionsStoreFactory
  # sessionsStoreFactory: com.unicodecollective.dropwizard.hazelcast.session.HazelcastSessionsStoreFactory
  # sessionsStoreFactory: com.unicodecollective.dropwizard.hazelcast.session.InMemorySessionsStoreFactory
  sessionTimeoutSecs: 600
  cookie:
    name: example-session

views:
  .ftl:
    strict_syntax: yes

logging:
  level: INFO
  loggers:
    com.hazelcast: INFO