server:
  applicationConnectors:
    - type: http
      port: 8180
  adminConnectors:
    - type: http
      port: 8181

hazelcastSessionConfig:
  sessionTimeoutSecs: 10
  cookieName: example-session

views:
  .ftl:
    strict_syntax: yes

logging:
  level: INFO
  loggers:
    com.hazelcast: INFO